### ISSUE TITLE
Pipeline with write_disposition="merge" fails when using timestamps

### ISSUE THREAD

**Issue by azngeek** [dlt-hub/dlt#811] opened 2023-12-08 15:36 UTC
### dlt version

dlt 0.3.25

### Describe the problem

I am trying to run an update against postgresql using a JSON-file. The JSON-file contains date-columns, which should be mapped as timestamp.

This is the case as the schema also describes it correctly. However if i try to run the pipeline, i will get an error.

```yaml
      changed_date:
        data_type: timestamp
        nullable: true
```

### Expected behavior

The pipeline will terminate with the following error:

```bash

dlt.destinations.exceptions.DatabaseTerminalException: column "changed_date" is of type timestamp with time zone but expression is of type character varying
LINE 20: ..._dlt_list_idx", "_dlt_id", "_dlt_root_id") SELECT "changed_d...
                                                              ^
HINT:  You will need to rewrite or cast the expression.
```

### Steps to reproduce

1. Configure a pipeline which runs against postregs
2. Use this attached dataset: 
[sample_changed_date.json](https://github.com/dlt-hub/dlt/files/13617309/sample_changed_date.json)
3. Ensure that you use write_disposition=merge
4. Run the pipeline and you will encounter the reported error
5. Change the mode to write_disposition=append
6. Pipeline will suceed

```python
    pipeline = dlt.pipeline(
        pipeline_name='test', 
        destination='postgres',
        dataset_name='test_data',
        credentials=credentials
    )
    load_info = pipeline.run(all_downloaded_products, table_name="products", write_disposition="merge")
```

### Operating system

macOS

### Runtime environment

Local

### Python version

3.11

### dlt data source

I am using a JSON-file

### dlt destination

Postgres

**Comment by rudolfix** [comment] 2023-12-10 17:24
@azngeek what is the `primary_key` or `merge_key`? I do not see it specified. but surely something we need to investigate! thanks for the report!

**Comment by azngeek** [comment] 2023-12-11 09:24
Oh i did not see, that this was required. I did not get an exception about missing keys. Maybe this would also be another task.

**Comment by sultaniman** [comment] 2024-01-10 09:47
@azngeek I've tried to reproduce the error using the version you have specified and the latest version (`0.4.2`) and everything worked without any error.

Here is an example script I used

```py
import json
import dlt

all_downloaded_products = json.load(open("sample_changed_date.json"))

pipeline = dlt.pipeline(
    pipeline_name="issue_811",
    destination="postgres",
    dataset_name="test_data",
)

load_info = pipeline.run(
    all_downloaded_products,
    table_name="products",
    write_disposition="merge",
)

print(load_info)
```

I ran the pipeline few times as well 
<img width="402" alt="image" src="https://github.com/dlt-hub/dlt/assets/354868/6b061695-be2c-470d-9192-68ced56c10b7">

If possible can you please provide your version of pipeline code?

**Comment by sultaniman** [comment] 2024-01-11 09:54
@azngeek can you please try to flush the state of pipeline maybe something got stale?

**Comment by sultaniman** [comment] 2024-01-22 13:09
Closing this issue, because there is no feedback from the author.

**Closed by sultaniman** 2024-01-22 13:09 UTC
Labels: bug
