### ISSUE TITLE
Docs sidebar UI bug: Navigation bar hidden under window edge

### ISSUE THREAD

**Issue by burnash** [dlt-hub/dlt#650] opened 2023-09-22 09:32 UTC
### dlt version

n/a

### Describe the problem

When navigating through the documentation at Reference > API > common > common.configuration, the sidebar shifts to the left, resulting in the left edge of the sidebar becoming hidden under the window edge. This affects the user's ability to navigate through the documentation as some of the options and text on the sidebar are not fully visible.

<img width="1582" alt="Screenshot 2023-09-22 at 12 25 29" src="https://github.com/dlt-hub/dlt/assets/264674/ac36340b-6ab7-4171-9b77-3adf5215cc94">

### Expected behavior

The sidebar should remain fully visible with all text and navigation options easily accessible, regardless of the user's navigation path through the documentation.

### Steps to reproduce

1. Open the https://dlthub.com/docs/
2. Navigate to Reference > API > common.
3. Click on common.configuration.

### Operating system

macOS

### Runtime environment

Other

### Python version

3.11

**Comment by deanja** [comment] 2023-12-02 02:55
A quick fix for this is to slightly widen the sidebar  (by 25 pixels) and to allow the user to hide the sidebar.

I have coded those changes.  Please assign me the issue and I will raise a PR.

The issue is caused by long module namespaces in the API, for example, `common.configuration.providers`., which cause wide menu items in the sidebar.   If an even wider namespace is introduced then `--doc-sidebar-width` could be increased again, within reason.    To mitigate the effects on usability, my change gives users the ability to hide the sidebar if it is distracting them from reading a document.

An alternative solution would be to limit/truncate API namespaces when generating the API documentation.

**Comment by burnash** [comment] 2023-12-04 18:41
Hey @deanja, thanks for proposing the fix. I like it. I think it's a practical way to fix. Please submit a PR with suggested changes.

**Closed** 2023-12-12 13:41 UTC
Labels: bug, documentation
